### ISSUE TITLE
SQL-injection через $_REQUEST search

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/Selector#1]
Вместо такого поведения

``` php
$search = is_scalar($_REQUEST['search']) ? $_REQUEST['search'] : '';
$searchQuery[] = "c.{$field} LIKE '%{$search}%'";
```

Рекомендуется использовать [следующий код из комплекта DocLister](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/lib/sqlHelper.class.php#L63):

``` php
sqlHelper::LikeEscape($modx, "c.{$field}", $search);
```

А еще лучше воспользоваться фильтром like так же, как это делается ниже

``` php
$filters[] = "tv:{$tv}:like:{$search}";
```

**Comment by Pathologic** [comment]
Глянь коммит

**Comment by AgelxNash** [comment]
Теперь все норм.
