### ISSUE TITLE
Снова нет крошек

### ISSUE THREAD

**Issue by Aharito** [Pathologic/Selector#11]
После последней правки снова нету крошек. Кеш MODx чистил.
![image](https://cloud.githubusercontent.com/assets/6253807/25696101/0e299282-30e0-11e7-80c1-aaa0c61a7df4.png)

**Comment by Pathologic** [comment]
Не знаю, почему у тебя нет крошек.
![fdgfg](https://cloud.githubusercontent.com/assets/3012304/25698406/6034f346-30c7-11e7-9058-cf144560b24b.png

**Comment by Pathologic** [comment]
https://github.com/Pathologic/Selector/issues/7#issuecomment-298176880 - у тебя DLcrumbs то работает, то не работает.

**Comment by Aharito** [comment]
Это у меня на локалке не работало на OpenServer (PHP 5.5). А на хостинг перенёс - как ни странно, заработало (PHP 5.3).

P.S. Сам DLcrumbs у меня **работает**, а вот **конфиг** для него не брался почему-то. В конфиге единственный параметр нужен - **&sysKey = \`crumbs\`**, вот его и не хватало для работы.
