### ISSUE TITLE
[Предложение] Ограничение на количество выбираемых пунктов

### ISSUE THREAD

**Issue by bagi091** [Pathologic/Selector#3]
Уже везде использую это решение, но лично мне не хватает возможности указывать сколько документов можно выбрать. 

Сейчас это реализовывается немного не удобно, через создание копии selector.tpl и selector.customtv.php

Пишу сюда, так как пока мыслей о том, как это сделать красивее у самого нет.

**Comment by Pathologic** [comment]
А что именно нужно ограничивать? Количество пунктов в выпадающем списке или итоговое?

**Comment by bagi091** [comment]
Итоговое

**Comment by Pathologic** [comment]
Понятно, нужно прикручивать конфиги. Сделаю на следующей неделе.
