### ISSUE TITLE
Неверный плейсхолдер

### ISSUE THREAD

**Issue by Aharito** [Pathologic/Selector#7]
![image](https://cloud.githubusercontent.com/assets/6253807/25555046/01e506dc-2d07-11e7-83d6-dabc2103f139.png)

**Comment by Pathologic** [comment]
А у меня почему работает?

**Comment by Pathologic** [comment]
Вот почему: https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/snippet.DLcrumbs.php#L33

**Comment by Aharito** [comment]
У меня всё то же самое, и DLcrumbs есть, и файл конфига есть такой же... смотрю, в чём дело.

**Comment by Aharito** [comment]
У тебя, видимо, версия не 9.1.3, а 7.1.6?

1) Я поставил в шаблон страницы вызов `[!DLcrumbs!]`, смотрю страницу на фронте - и конфиг **не** берётся. А у тебя, получается, берется. Значит, это, видимо косяк новой версии...

2) Тот конфиг **crumb:core**, что по умолчанию в DLcrumbs, по идее и **не нужен** - он по schema.org сделан, из него используется **только** параметр sysKey да debug.

3) В итоге не проще ли добавить [после этой строки](https://github.com/Pathologic/Selector/blob/master/assets/tvs/selector/lib/controller.class.php#L77) строку `'sysKey'     => 'crumb'`, чтобы работало даже и сейчас, когда конфиг не берётся почему-то?

**Comment by Pathologic** [comment]
Так надо разобраться, почему так. Я проверял на https://github.com/Pathologic/evolution - 1.2.2 там написано.

**Comment by Aharito** [comment]
Разберусь со временем, пока не понимаю, в чем дело.
